"""Systematic test: try every command in every situation.
Run: python3 systematic_test.py"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from game.engine import GameState, process_command, handle_look, LOCATIONS
from game import world

s = GameState()
log = []

def test(situation, command, expected_behavior=None):
    """Run a command and log what happens."""
    try:
        result = process_command(s, command)
        preview = result[:120].replace('\n', '|')
        log.append(f"{situation:40s} | {command:25s} | {preview}")
    except Exception as e:
        log.append(f"{situation:40s} | {command:25s} | ⚠ EXCEPTION: {e}")

# ─── BASIC COMMANDS AT HOME ───
test("Fresh game", "look")
test("Talk to druid", "talk to druid")
test("No args: talk", "talk")
test("No target: talk to", "talk to")
test("Talk to nonexistent", "talk to unicorn")
test("Take magic thread", "take thread")
test("Take provisions", "take provisions")
test("Take nonexistent", "take blorple")
test("No args: take", "take")
test("Inventory", "i")
test("Empty examine", "examine")
test("Examine item", "examine thread")
test("Examine NPC", "examine druid")
test("Examine nonsense", "examine xyzzy")
test("Drop inventory item", "drop thread")
test("Drop nonexistent", "drop unicorn")
test("No args: drop", "drop")
test("Give no args", "give")
test("Give item to NPC", "give provisions to druid")
test("Give wrong item", "give thread to druid")
test("Use no args", "use")
test("Use item", "use thread")
test("Help", "help")
test("Score", "score")
test("Crew", "crew")
test("Wait", "wait")
test("Unknown command", "xyzzy")
test("Home direction", "home")
test("Empty command", "")

# ─── SEA NAVIGATION ───
test("Sail west", "west")
test("Sail invalid dir", "north")
test("Go deeper", "deeper")
test("Go back", "back")
test("Sail from sea", "sail")
test("Look at sea", "look")
test("Go to culdees", "north")
test("Talk no one here", "talk to nobody")
test("Take silver bell", "take bell")
test("Return", "south")
test("Go deeper", "deeper")
test("Go further", "deeper")
test("Go home", "home")

# ─── ENDING ───
test("Look homecoming", "look")
test("Fight raiders", "fight raiders")
test("Say yes to ending", "yes")

# ─── SECOND PLAYTHROUGH: TEST MORE EDGE CASES ───
s2 = GameState()
test("2P: fresh look", "look")
test("2P: take thread", "take thread")
test("2P: west to sea", "west")
test("2P: north to birds", "north")
test("2P: examine birds", "look")
test("2P: take feather", "take feather")
test("2P: climb nest", "up")
test("2P: return", "down")
test("2P: return sea", "south")
test("2P: northeast cat", "northeast")
test("2P: take milk", "take milk")
test("2P: give cat milk", "give milk to cat")
test("2P: give cat wrong", "give feather to cat")
test("2P: return", "southwest")
test("2P: east laughing", "east")
test("2P: talk king", "talk to king")
test("2P: tell joke", "joke why did the salmon")
test("2P: joke again", "joke knock knock")
test("2P: return", "west")
test("2P: south bridge", "south")
test("2P: cross bridge", "cross")
test("2P: return", "back")
test("2P: return sea", "north")
test("2P: nw smithy", "northwest")
test("2P: talk smith", "talk to smith")
test("2P: return", "southeast")
test("2P: se women", "southeast")
test("2P: talk queen", "talk to queen")
test("2P: say no to queen", "no")
test("2P: return", "northwest")
test("2P: sw monsters", "southwest")
test("2P: fight monster", "fight monster")
test("2P: fight again", "fight monster")
test("2P: return", "northeast")
test("2P: sing at sea", "sing green hills")
test("2P: go deeper", "deeper")
test("2P: east hermit", "east")
test("2P: talk hermit", "talk to hermit")
test("2P: take pelt", "take pelt")
test("2P: return", "west")
test("2P: west fences", "west")
test("2P: return", "east")
test("2P: south tower", "south")
test("2P: talk prophet", "talk to boy")
test("2P: take scroll", "take scroll")
test("2P: return", "north")
test("2P: deeper again", "deeper")
test("2P: north serpent", "north")
test("2P: take herb", "take herb")
test("2P: return", "south")
test("2P: east pig", "east")
test("2P: take apple", "take apple")
test("2P: fight pig", "fight pig")
test("2P: return", "west")
test("2P: west skull", "west")
test("2P: talk skull", "talk to skull")
test("2P: return", "east")
test("2P: south horse", "south")
test("2P: talk horse", "talk to horse")
test("2P: return", "north")
test("2P: ne fiery pigs", "northeast")
test("2P: look pigs", "look")
test("2P: return", "southwest")
test("2P: nw castle", "northwest")
test("2P: look castle", "look")
test("2P: return", "southeast")
test("2P: trumpet", "southeast")
test("2P: take earplugs", "take earplugs")
test("2P: return", "northwest")
test("2P: sw demon", "southwest")
test("2P: talk demon", "talk to demon")
test("2P: take coin", "take coin")
test("2P: return", "northeast")
test("2P: gold pillar", "gold")
test("2P: return", "northeast")
test("2P: inventory full", "i")
test("2P: try drop bunch", "drop provisions")
test("2P: try take apple", "take apple")

# ─── RESULTS ───
print(f"\n{'='*80}")
print(f"SYSTEMATIC TEST: {len(log)} commands executed")
print(f"{'='*80}")

# Check for errors
errors = [l for l in log if '⚠' in l or 'EXCEPTION' in l or 'I don\'t understand' in l]
empty_results = [l for l in log if l.endswith('| ') or l.endswith('| None')]

if errors:
    print(f"\n⚠ {len(errors)} ERRORS:")
    for e in errors:
        print(f"  {e}")
else:
    print(f"\n✓ No errors found")

# Print all results
print(f"\n{'─'*80}")
print("FULL LOG:")
print(f"{'─'*80}")
for l in log:
    print(l)
